### ISSUE TITLE
Unit test "OAP accumulators on Parquet when hit index" in OapMetricsSuite fails randomly 

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#525] opened 2018-01-16 08:26 UTC
This happens randomly
```
- get columns hit index
22:57:18.107 WARN org.apache.spark.sql.execution.datasources.oap.index.BPlusTreeScanner: OAP index is skipped. Disable OAP_EXECUTOR_INDEX_SELECTION to use index.
22:57:18.154 WARN org.apache.spark.sql.execution.datasources.oap.index.BPlusTreeScanner: OAP index is skipped. Disable OAP_EXECUTOR_INDEX_SELECTION to use index.
- skipped rows and selected rows *** FAILED ***
  1 did not equal 33 (FilterSuite.scala:962)
```
Full log at https://travis-ci.org/Intel-bigdata/OAP/builds/329340068?utm_source=github_status&utm_medium=notification

**Comment by carsonwang** [comment] 2018-01-16 08:29
Also cc @TigerSong

**Comment by linhong-intel** [comment] 2018-01-17 02:04
I'll check with @TigerSong on Thursday.
So assign to both of us.

**Comment by TigerSong** [comment] 2018-01-18 06:24
Thanks @carsonwang ，I'll check it

**Comment by TigerSong** [comment] 2018-01-22 06:08
Can you show more cases? I test it on mac for several times, all tests successful. 
it seems that the failed test miss the index.

**Comment by linhong-intel** [comment] 2018-04-16 07:55
change title since test case name is changed. @songzhan01 is tracking this.

**Comment by linhong-intel** [comment] 2018-05-31 03:43
root cause:
In test suite sample size of `SampleBasedStatistics` is *one*.
So, this means this stat only output USE_INDEX or FULL_SCAN.

**Closed** 2018-05-31 07:05 UTC

**Comment by gczsjdy** [comment] 2018-05-31 07:35
@linhong-intel You actually mean sample size is 0 ?

**Comment by linhong-intel** [comment] 2018-05-31 08:29
@gczsjdy I'll explain this a little bit and we can have a offline discuss if you still have question.

**Comment by gczsjdy** [comment] 2018-05-31 10:56
Thanks @linhong-intel
