### ISSUE TITLE
Refactor the way of configuration 

### ISSUE THREAD

**Issue by shimingfei** [Intel-bigdata/OAP#63] opened 2016-05-26 10:48 UTC
Currently, the some configurable parameters are either set to default or gotten from JVM properties.
we need to uniform the way of configuring those parameters.

**Comment by linhong-intel** [comment] 2017-06-08 02:29
Duplicate of issue #235

**Comment by adrian-wang** [comment] 2017-06-09 06:42
Close as duplicate

**Closed by adrian-wang** 2017-06-09 06:42 UTC
Labels: duplicate
