### ISSUE TITLE
[0.3.0 QA] Under 40g onheap setting, there seems to be performance issues for Bitmap index. 

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#513] opened 2018-01-16 02:57 UTC
Reporter: Yang
Need investigate if the onheap memory is not enough and causes some gc. Will tune it to compare gc time and performance.

**Comment by lee-lei** [comment] 2018-01-17 02:56
@xuyangit Would you please share which test case and what configurations you used. I will first reproduce this issue and analyze the root cause. Thanks.

**Comment by lee-lei** [comment] 2018-01-17 03:01
It seems that I can't assign the issue to me. @linhong-intel Would you please help assign this issue to me? Thanks.

**Comment by lee-lei** [comment] 2018-01-17 10:55
I ran only bitmap index tests on the five haswell IA clusters. The data shows that the task time is from 27 min to 1.2 hour. The GC time is always around 2 ~ 3 seconds. IMHO, it may not be a big issue. Thanks.

**Comment by lee-lei** [comment] 2018-01-17 11:45
From the result, the q2, q4, q5, q7 is worst w/ index than w/o index. For the other 7 cases, index result is better than w/o index. The analysis for thests cases are WIP.

**Comment by yueawang** [comment] 2018-01-18 01:32
Two things need to be addressed:
1. Bitmap does not enable statistics check.
2. Bitmap seems introduces too much GC especially in concurrency mode.

**Comment by lee-lei** [comment] 2018-01-22 02:48
I will create a PR to address the above part 1. For the above part 2, from my experiment, the task GC time is very short in total task time as I said above. @yueawang Would you please help describe the concurrency mode so that I will reproduce and analyze the root cause? Thanks.

**Comment by yueawang** [comment] 2018-01-22 03:29
[beeline-cmds.py.txt](https://github.com/Intel-bigdata/OAP/files/1650632/beeline-cmds.py.txt)
This script tries to commit beeline jobs in parallel. you can build few columns w/ bitmap index, and then check if it works as expected in your setup. My env is to test memory pressure, by using this script, it seems more GC are brought by bitmap index.

**Comment by lee-lei** [comment] 2018-01-22 05:26
Got it. Thanks!

**Comment by lee-lei** [comment] 2018-01-22 05:33
@adrian-wang I will take this issue. Please help assign it to me. Thanks.

**Comment by lee-lei** [comment] 2018-01-22 11:21
The above part 1 is addressed by the PR#539. Thanks.

**Comment by lee-lei** [comment] 2018-01-29 04:58
For the above part 2, the memory configuration is decreased by 25%, and the data set size is increased by 4X. Under this stress mode configuration, the GC count for bitmap is below 300. And the majority of the GC collection time is below 0.01 seconds. The total GC collection time is around tens of seconds. I think this kind of GC behavior is reasonable for the stree mode tests. Thanks.

**Closed** 2018-04-02 06:41 UTC
