### ISSUE TITLE
[0.3.0 QA] For Bitmap, the performance of cache is not very obvious compared to B-Tree. 

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#512] opened 2018-01-16 02:56 UTC
Reporter: Yang

**Comment by lee-lei** [comment] 2018-01-16 06:33
On the one hand, the performance test cases are different for bitmap and btree. It's not apple-to-apple comparison. On the other hand, IMHO, the data size involved by each test case are quite different for bitmap and btree. In normal cases, the data size is much smaller for bitmap than btree. The load time/total time percent is smaller. In other words, to some extent, it's expected that the cache impact may not be obvious for bitmap if the load time is removed out of the total time. In addition, the os will be more easy to cache the smaller size data. Please doule check to aovid the impact of the os cache.

**Comment by chenghao-intel** [comment] 2018-01-17 01:18
@lee-lei since we have the data and environment, maybe you'd better to check the root cause, sorry I am not sure if have done the analysis from the data and testing? Or just "guessing".

**Comment by lee-lei** [comment] 2018-01-17 02:52
The test cases for performance evaluation are totally different between btree and bitmap. In order to get apple-to-apple comparison, we will first to get the data from the same test cases for both btree and bitmap. Thanks.

**Comment by lee-lei** [comment] 2018-01-17 03:01
@linhong-intel Would you please help assign this issue to me? Thanks.

**Comment by lee-lei** [comment] 2018-01-17 11:10
For this issue, as I said above, as the first step we will get the data for the same test cases. Take bitmap index test cases as the example, we will create both btree and bitmap index for the same attribute on the same table. And then run these same test cases respectively. Thanks.

**Comment by lee-lei** [comment] 2018-01-22 05:33
@adrian-wang I will take this issue. Please help assign it to me. Thanks.

**Comment by lee-lei** [comment] 2018-01-29 05:06
On the one hand, I double checked that Baidu is using bitmap index in their production environment because of its unique benefit. On the other hand, we also found some cases in highly repeated columnars, the bitmap query time is below half of btree query time.

**Comment by lee-lei** [comment] 2018-02-02 01:44
I am getting the equal query performance comparison based on the same data set with both btree and bitmap indexes for different columnars. The data scale is at GB and TB. After all the data is finalized, I will summarize them and update here. Stay tuned. Thanks.

**Comment by lee-lei** [comment] 2018-02-05 04:11
Below is the query time on store_sales of 1TB TPCDS data. The unit is milliseconds.			
ss_quantity (1-100)	|| large range equal query || middle range equal query || single equal query
index w/ Btree	125059	100759	86026
index w/ Bitmap	85851	91026	72157
ss_promo_sk (1-1500)			
index w/ Btree	77851	77830	69244
index w/ Bitmap	70057	69475	69436
ss_ticket_number (1-240m)			
index w/ Btree	136084	111673	11877
index w/ Bitmap	14792	9842	1642
ss_item_sk1 (1-1001)			
index w/ Btree	73883	71829	70237
index w/ Bitmap	88922	89134	87364

**Comment by lee-lei** [comment] 2018-02-05 04:12
Below is the query time on store_sales of 200GB TPCDS data. The unit is milliseconds.
ss_quantity (1-100)	|| large range equal query || middle range equal query || single equal query
index w/ Btree	23822	12897	11849
index w/ Bitmap	12564	10866	10823
ss_promo_sk (1-1500)			
index w/ Btree	10432	11246	8761
index w/ Bitmap	10218	10085	9240
ss_ticket_number (1-240m)			
index w/ Btree	24891	17745	3940
index w/ Bitmap	3346	2304	1447
ss_item_sk1 (1-1001)			
index w/ Btree	10944	9959	9357
index w/ Bitmap	13878	12022	14635

**Comment by lee-lei** [comment] 2018-02-05 04:14
Below is the query time on store_sales of 100GB TPCDS data. The unit is milliseconds.
ss_quantity (1-100)	|| large range equal query || middle range equal query || single equal query
index w/ Btree	6979	4494	4165
index w/ Bitmap	5397	4926	994
ss_promo_sk (1-1500)			
index w/ Btree	4898	4697	3352
index w/ Bitmap	829	542	308
ss_ticket_number (1-240m)	8554	8891	5418
index w/ Btree	2350	2251	443
index w/ Bitmap			
ss_item_sk1 (1-1001)			
index w/ Btree	4148	705	4520
index w/ Bitmap	6934	3802	6005

**Comment by lee-lei** [comment] 2018-02-05 04:15
Below is the query time on store_sales of 10GB TPCDS data. The unit is milliseconds.
ss_quantity (1-100)	|| large range equal query || middle range equal query || single equal query
index w/ Btree	678	412	866
index w/ Bitmap	625	835	255
ss_promo_sk (1-1500)			
index w/ Btree	377	764	801
index w/ Bitmap	260	759	195
ss_ticket_number (1-240m)			
index w/ Btree	760	247	162
index w/ Bitmap	938	887	214
ss_item_sk1 (1-1001)			
index w/ Btree	363	247	217
index w/ Bitmap	771	283	224

**Comment by lee-lei** [comment] 2018-02-05 04:18
The ss_item_sk1 is one additionally added column with 1001 unique values. Other three columns are the default on store_sales table with 100, 1500 and 240m unique values. From the above data, the bitmap performance is better than btree in most cases for three default columns. For ss_item_sk1, the new appended columns, the bitmap performance is worse than btree. The root cause analysis is WIP.

**Closed** 2018-04-09 06:18 UTC
