### ISSUE TITLE
“Enable/disable using OAP index after the index is created already ” not pass

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#502] opened 2018-01-09 06:29 UTC
Test Case “Enable/disable using OAP index after the index is created already ”  in OapSuite not paas when i run this case alone(run with intellij test by name mode) ，but pass when run all test case in OapSuite(run with intellij test by class mode) . Is there  parameters missing?

**Comment by linhong-intel** [comment] 2018-01-10 00:55
@lee-lei Can you check this?

**Comment by lee-lei** [comment] 2018-01-10 07:29
Based on the latest code base, I used below command. And the test case OapSuite passed.
mvn -DwildcardSuites=org.apache.spark.sql.execution.datasources.oap.OapSuite test

Can you help double check it? Thanks.

**Comment by carsonwang** [comment] 2018-01-10 07:45
As the problem description says, I think we need run the single unit test case instead of the whole suite to reproduce the issue.

**Comment by linhong-intel** [comment] 2018-01-10 08:45
@lee-lei 
I can reproduce it with single test running in IDE

**Comment by LuciferYang** [comment] 2018-01-10 08:49
@lee-lei @linhong-intel  as @carsonwang  said, run the single unit test “Enable/disable using OAP index after the index is created already ”

**Comment by adrian-wang** [comment] 2018-01-10 08:58
This results from the test case before it. By set compressionCodec to UNCOMPRESSED for this case, the test will pass. Should look further into the case to tell why compression codec matters.

**Comment by lee-lei** [comment] 2018-01-10 09:07
Thanks!

**Comment by Moonlit-Sailor** [comment] 2018-01-11 05:14
this is caused by index file size > data file size * `OAP_INDEX_FILE_SIZE_MAX_RATIO`, therefore, executor will not use index.
To fix it, we could simply set `OAP_ENABLE_EXECUTOR_INDEX_SELECTION` to false to force executor to use index

**Comment by linhong-intel** [comment] 2018-01-11 05:53
> this is caused by index file size > data file size * OAP_INDEX_FILE_SIZE_MAX_RATIO, therefore, executor will not use index.

I still don't see why only failed with single unit test

**Comment by linhong-intel** [comment] 2018-01-11 05:54
So, the problem is:
when we set compress enable then index size is less than data size, so every thing is ok.
if we don't set compress enable, we can skip index size check, so it also works.
right?

**Comment by adrian-wang** [comment] 2018-01-11 05:56
The problem is the test prior to this set compression type to uncompressed, hence the data file size becomes larger, while index file size is not affected. so run them together is OK, but when run the single test, the default compression is still snappy and the index will be skipped.

**Comment by adrian-wang** [comment] 2018-01-11 05:57
@linhong-intel compression is enabled by default, only the test prior to this disabled compression by accident.

**Comment by yueawang** [comment] 2018-01-11 06:08
For index file size > data file size * OAP_INDEX_FILE_SIZE_MAX_RATION 
All test case based on SharedOAPContext disabled this check by setting a flag to control this specific option, @Moonlit-Sailor don't need to disable full executor index selection, as statistics may still take effect.

**Comment by yueawang** [comment] 2018-01-11 06:23
In SharedOapContext, we have.
  // disable file based cbo for all test suite, as it always fails.
  sparkConf.set(SQLConf.OAP_EXECUTOR_INDEX_SELECTION_FILE_POLICY.key, "false")

Any reason this flag changes??

**Comment by adrian-wang** [comment] 2018-01-11 06:59
@yueawang when you access `OAP_EXECUTOR_INDEX_SELECTION_FILE_POLICY` in IndexScanner, you tried to read from `conf`, while `conf` is a hadoop configuration, which is not affected by the settings you set in SharedOapContext.

**Comment by yueawang** [comment] 2018-01-11 07:28
This test loads its own conf, PR #507 to make it use the one from SharedOapContext.

**Comment by lee-lei** [comment] 2018-01-11 08:32
In our index scanners, one index selection policy is that we will check if the index file size is greater than the ratio(default is 0.7) of oap data file size. If greater, then use full scan. If not, use index instead. The oap data file size here is the compressed size rather than the raw file size if it's compressed by default. The "SNAPPY" and "GZIP" have the good compression ratio. The compressed oap data file size is much smaller. For this test case, with our index selection policy, it will use full scan rather than index. With "UNCOMPRESSED" or "LZO", the oap data file size is larger. So the index selection policy will decide to use index for this test case.

**Comment by lee-lei** [comment] 2018-01-11 09:17
So far, it's unfair to compare the raw uncompressed index file size and the compressed oap data file size before deciding to use index or not.

**Comment by yueawang** [comment] 2018-01-11 14:45
Yes, so I also restore the compression format back after previous test case. basically this issue is because 1. it uses its own conf which does not disable file size check. 2. The case above changed compression type to UNCOMPRESS.

**Comment by lee-lei** [comment] 2018-01-12 02:36
To be honest, it's just a workaround approach to disable the index selection file policy for all the tests. Meanwhile, it won't test this policy any more after disabling it. IMHO, it's ok to just pass the tests for 0.3.0 release. In the next release, it's better to elegantly resolve the real issue and enable this policy for the tests to validate it, since the file policy is enabled by default in the production environment.

**Comment by linhong-intel** [comment] 2018-01-12 09:40
fixed by #507 
@lee-lei , please file a new bug with a precise description to track the real issue.

**Closed by linhong-intel** 2018-01-12 09:40 UTC
Labels: bug

**Comment by lee-lei** [comment] 2018-01-15 05:10
The issue #509 will track this real issue. It's expected to finish it in the next 0.4.0 release Thanks.
