### ISSUE TITLE
[OAP-CACHE] Error runing q32 binary cache

### ISSUE THREAD

**Issue by offthewall123** [Intel-bigdata/OAP#1981] opened 2020-12-01 10:54 UTC
core dump running q32 using binary cache

**Comment by zhixingheyi-tian** [comment] 2020-12-02 01:13
@offthewall123  mark this as "OAP 1.0"?

**Comment by offthewall123** [comment] 2020-12-02 01:18
@zhixingheyi-tian No, it's 0.8 branch.

**Comment by jikunshang** [comment] 2020-12-02 01:49
closed since PR got merged.

**Comment by jikunshang** [comment] 2020-12-11 10:04
@HongW2019 reproduce this issue on branch-1.0. Analyze code again, need some more fix.

**Comment by offthewall123** [comment] 2020-12-11 10:30
LGTM.

**Closed** 2020-12-12 02:28 UTC
Labels: OAP 0.8, bug
